const colors = {
  light: {
    // Light mode mirrors dark mode but INVERTED:
    // dark = navy cards + gold UI  →  light = gold cards + navy UI
    // background goes black→white, gold↔navy swap on cards/primary
    text: "#0B1B5E",
    tint: "#0B1B5E",
    background: "#EEF1FF",
    foreground: "#0B1B5E",
    // Cards are shiny bright gold — navy cards live in dark mode
    card: "#E8B800",
    cardForeground: "#0B1B5E",
    // Navy is the primary interactive colour in light mode
    primary: "#0B1B5E",
    primaryForeground: "#FFFFFF",
    secondary: "#C89A00",        // deeper gold for secondary fills
    secondaryForeground: "#0B1B5E",
    muted: "#FFF6CC",            // warm cream
    mutedForeground: "#7A5F00",
    accent: "#0B1B5E",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    greenLight: "#DCFCE7",
    green: "#16A34A",
    successForeground: "#166534",
    success: "#DCFCE7",
    successFeedback: "#065F46",
    successFeedbackBackground: "#ECFDF5",
    successBadge: "#047857",
    successStatusText: "#064E3B",
    border: "#C89A00",
    input: "#D4A800",
    // Gold token — always the SHINY vivid gold
    gold: "#E8B800",
    goldText: "#7A5F00",
    goldLight: "#FFF9DA",
    onGold: "#0B1B5E",
    destructiveText: "#7F1D1D",
    destructiveFeedback: "#991B1B",
    destructiveFeedbackBackground: "#FEF2F2",
    destructiveBadge: "#B91C1C",
    primaryAccentForeground: "#E8B800",
    primaryMutedForeground: "rgba(255,255,255,0.7)",
    navy: "#0B1B5E",
  },
  dark: {
    // Dark mode: navy cards + shiny gold UI — the inverse of light mode
    text: "#E6EAF8",
    tint: "#E8B800",
    background: "#05070D",
    foreground: "#E6EAF8",
    // Cards are navy — gold cards live in light mode
    card: "#0B1B5E",
    cardForeground: "#FFFFFF",
    // Gold is the primary interactive colour in dark mode
    primary: "#E8B800",
    primaryForeground: "#0B1B5E",
    secondary: "#142070",
    secondaryForeground: "#FFFFFF",
    muted: "#162258",
    mutedForeground: "#9CA3AF",
    accent: "#E8B800",
    accentForeground: "#0B1B5E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    greenLight: "#14351F",
    green: "#4ADE80",
    successForeground: "#BBF7D0",
    success: "#14532D",
    successFeedback: "#065F46",
    successFeedbackBackground: "#ECFDF5",
    successBadge: "#047857",
    successStatusText: "#BBF7D0",
    border: "#1A2E80",
    input: "#1A2E80",
    gold: "#E8B800",
    goldText: "#E8B800",
    goldLight: "#241C04",
    onGold: "#0B1B5E",
    destructiveText: "#FCA5A5",
    destructiveFeedback: "#991B1B",
    destructiveFeedbackBackground: "#FEF2F2",
    destructiveBadge: "#B91C1C",
    primaryAccentForeground: "#0B1B5E",
    primaryMutedForeground: "#0B1B5E",
    navy: "#E6EAF8",
  },
  radius: 16,
};

export default colors;
