const colors = {
  light: {
    text: "#0B1B5E",
    tint: "#0B1B5E",
    background: "#F5F7FF",
    foreground: "#0B1B5E",
    // Cards are clean white — gold used only as an accent, not a fill
    card: "#FFFFFF",
    cardForeground: "#0B1B5E",
    primary: "#0B1B5E",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF1FF",
    secondaryForeground: "#0B1B5E",
    muted: "#F4F6FF",
    mutedForeground: "#7B8BB2",
    accent: "#C49A0A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    // Gold is an accent only — borders, icons, left bars, badges
    gold: "#C49A0A",
    goldLight: "#FFF9E6",
    navy: "#0B1B5E",
  },
  dark: {
    text: "#E6EAF8",
    tint: "#C49A0A",
    background: "#05070D",
    foreground: "#E6EAF8",
    card: "#0B1B5E",
    cardForeground: "#FFFFFF",
    primary: "#C49A0A",
    primaryForeground: "#0B1B5E",
    secondary: "#142070",
    secondaryForeground: "#FFFFFF",
    muted: "#162258",
    mutedForeground: "#9CA3AF",
    accent: "#C49A0A",
    accentForeground: "#0B1B5E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1A2E80",
    input: "#1A2E80",
    gold: "#C49A0A",
    goldLight: "#241C04",
    navy: "#E6EAF8",
  },
  radius: 16,
};

export default colors;
