const colors = {
  light: {
    text: "#0B1B5E",
    tint: "#0B1B5E",
    background: "#F5F7FF",
    foreground: "#0B1B5E",
    // Cards are gold — the signature royal colour of the RA app
    card: "#D4A217",
    cardForeground: "#0B1B5E",
    primary: "#0B1B5E",
    primaryForeground: "#FFFFFF",
    secondary: "#C49210",
    secondaryForeground: "#FFFFFF",
    muted: "#EEF1FF",
    mutedForeground: "#9CA3AF",
    accent: "#D4A217",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#B8880E",
    input: "#E0E5F7",
    gold: "#D4A217",
    goldLight: "#FFF8E1",
    navy: "#0B1B5E",
  },
  dark: {
    text: "#E6EAF8",
    tint: "#D4A217",
    // Near-black background so navy elements are clearly distinguishable
    background: "#05070D",
    foreground: "#E6EAF8",
    // Cards and header are actual navy blue — visible against the black background
    card: "#0B1B5E",
    cardForeground: "#FFFFFF",
    // Gold is the primary interactive colour in dark mode
    primary: "#D4A217",
    primaryForeground: "#0B1B5E",
    secondary: "#142070",
    secondaryForeground: "#FFFFFF",
    muted: "#162258",
    mutedForeground: "#9CA3AF",
    accent: "#D4A217",
    accentForeground: "#0B1B5E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1A2E80",
    input: "#1A2E80",
    gold: "#D4A217",
    goldLight: "#241C04",
    navy: "#E6EAF8",
  },
  radius: 16,
};

export default colors;
